service: myDummyProject

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  dummyFunction:
    handler: handler.run

stepFunctions:
  validate: true
  stateMachines:
    dummyWorkflow:
      definition:
        Comment: Dummy workflow that calls a Lambda and then succeeds
        StartAt: InvokeLambda
        States:
          InvokeLambda:
            Type: Task
            Resource:
              Fn::GetAtt:
                - dummyFunction
                - Arn
            ResultPath: $.lambdaResult
            End: true
